### ISSUE TITLE
Unsure where/how to locate demo_clean.csv data set

### ISSUE THREAD

**Issue by AndrewNute** [itidat/tropical-data-analysis-public#1]
https://github.com/itidat/tropical-data-analysis-public/blob/f4e8db7df4e7ae4dd3221f2ecff3f27b1ba5d60e/TD_standard_analyses.R#L31

When trying to recreate the analysis outlined here, I was unable to locate the demo_clean.csv file  among the data sets published on this GitHub site with the "demo_" identifier.  Maybe I am confused about where to find that data.  If this is the case, I apologize.  Either way, I appreciate any guidance and clarification.

Is this supposed to be either a data set or a combination of data sets (absent, resident, and household) approved by the MoH which we have downloaded from the Tropical Data portal which is external to this repository?  Or was this intended to be posted in this repository for use as part of the walk through for the analysis?

**Comment by itidat** [comment]
Hi Andrew! I have just posted a newly coded version of the public analysis code to combine the v1 and v2 methodologies and to make it more fit for public use. Happy to receive your feedback whenever you have time to test it out. 

Ana
